# Generated by Django 4.0.2 on 2022-09-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BatutaTG', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='Authority',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
