# Generated by Django 4.0.2 on 2022-10-04 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BatutaTG', '0002_alter_admins_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='criticism',
            name='User_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BatutaTG.users'),
        ),
        migrations.AddField(
            model_name='surveys',
            name='DopInfo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
