# Generated by Django 4.0.2 on 2022-10-29 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BatutaTG', '0003_criticism_user_id_surveys_dopinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Restaurants_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BatutaTG.restaurant'),
        ),
        migrations.AddField(
            model_name='surveys',
            name='Restaurants_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BatutaTG.restaurant'),
        ),
        migrations.AlterField(
            model_name='criticism',
            name='Color',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='criticism',
            name='Read',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='criticism',
            name='User_id',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='BatutaTG.users'),
        ),
    ]
